version: '3.4'

services:
  
  jobdb:
    container_name: jobdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  jobs.api:
    container_name: jobs.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://jobdb:27017"
    depends_on:
      - jobdb
    ports:
      - "8000:80"